logging:
  level: INFO
  loggers:
    com.example: DEBUG
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

databaseUrl: jdbc:postgresql://localhost:5432/recipeDB
databaseUser: postgres
databasePassword: Leeames123!
